/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.awt.Graphics2D;
import java.io.PrintStream;
import javax.swing.Icon;
import java.awt.Dimension;
import java.awt.image.BufferedImageOp;
import java.awt.image.ConvolveOp;
import java.awt.image.Kernel;
import javax.swing.JColorChooser;

/**
 *
 * @author ASUS
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        this.setTitle("Editor");
        BufferedImage icon = null;
        try {
            icon = ImageIO.read(new File("icon.png"));
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        RbtnNone = new javax.swing.JRadioButton();
        RbtnBlur = new javax.swing.JRadioButton();
        RbtnRadian = new javax.swing.JRadioButton();
        RbtnSolbel = new javax.swing.JRadioButton();
        RbtnShape = new javax.swing.JRadioButton();
        RbtnGausse = new javax.swing.JRadioButton();
        LbImage = new javax.swing.JLabel();
        LbBoloc = new javax.swing.JLabel();
        Filter1_1 = new javax.swing.JTextField();
        Filter2_1 = new javax.swing.JTextField();
        Filter3_1 = new javax.swing.JTextField();
        Filter1_2 = new javax.swing.JTextField();
        Filter2_2 = new javax.swing.JTextField();
        Filter3_2 = new javax.swing.JTextField();
        Filter1_3 = new javax.swing.JTextField();
        Filter2_3 = new javax.swing.JTextField();
        Filter3_3 = new javax.swing.JTextField();
        RbtnCustom = new javax.swing.JRadioButton();
        LbBolocCustom = new javax.swing.JLabel();
        BtnProcess = new javax.swing.JButton();
        javax.swing.JToggleButton BtnPen = new javax.swing.JToggleButton();
        SliderPen = new javax.swing.JSlider();
        BtnColor = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        MenuItemNew = new javax.swing.JMenuItem();
        MenuItemOpen = new javax.swing.JMenuItem();
        MenuItemSave = new javax.swing.JMenuItem();
        MenuItemSaveAs = new javax.swing.JMenuItem();
        MenuItemExit = new javax.swing.JMenuItem();
        View = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(RbtnNone);
        RbtnNone.setSelected(true);
        RbtnNone.setText("None");
        RbtnNone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnNoneActionPerformed(evt);
            }
        });

        buttonGroup1.add(RbtnBlur);
        RbtnBlur.setText("Blur");

        buttonGroup1.add(RbtnRadian);
        RbtnRadian.setText("Radian");

        buttonGroup1.add(RbtnSolbel);
        RbtnSolbel.setText("Sobel");

        buttonGroup1.add(RbtnShape);
        RbtnShape.setText("Shape");

        buttonGroup1.add(RbtnGausse);
        RbtnGausse.setText("Gausse");

        LbImage.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LbImageMouseDragged(evt);
            }
        });
        LbImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbImageMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LbImageMousePressed(evt);
            }
        });

        LbBoloc.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        LbBoloc.setText("Bộ lọc");

        Filter1_1.setText("0");
        Filter1_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Filter1_1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Filter1_1MouseExited(evt);
            }
        });
        Filter1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filter1_1ActionPerformed(evt);
            }
        });

        Filter2_1.setText("0");
        Filter2_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Filter2_1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Filter2_1MouseExited(evt);
            }
        });

        Filter3_1.setText("0");
        Filter3_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Filter3_1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Filter3_1MouseExited(evt);
            }
        });

        Filter1_2.setText("0");
        Filter1_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Filter1_2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Filter1_2MouseExited(evt);
            }
        });
        Filter1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filter1_2ActionPerformed(evt);
            }
        });

        Filter2_2.setText("0");
        Filter2_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Filter2_2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Filter2_2MouseExited(evt);
            }
        });

        Filter3_2.setText("0");
        Filter3_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Filter3_2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Filter3_2MouseExited(evt);
            }
        });
        Filter3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filter3_2ActionPerformed(evt);
            }
        });

        Filter1_3.setText("0");
        Filter1_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Filter1_3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Filter1_3MouseExited(evt);
            }
        });
        Filter1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filter1_3ActionPerformed(evt);
            }
        });

        Filter2_3.setText("0");
        Filter2_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Filter2_3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Filter2_3MouseExited(evt);
            }
        });

        Filter3_3.setText("0");
        Filter3_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Filter3_3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Filter3_3MouseExited(evt);
            }
        });

        buttonGroup1.add(RbtnCustom);
        RbtnCustom.setText("Custom");

        LbBolocCustom.setText("Bộ lọc custom");

        BtnProcess.setText("Xử lý");
        BtnProcess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnProcessMouseClicked(evt);
            }
        });
        BtnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProcessActionPerformed(evt);
            }
        });

        BtnPen.setText("Pen");
        BtnPen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPenMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnPenMouseReleased(evt);
            }
        });
        BtnPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPenActionPerformed(evt);
            }
        });

        SliderPen.setMaximum(10);
        SliderPen.setPaintTicks(true);
        SliderPen.setMajorTickSpacing(1);
        SliderPen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderPenStateChanged(evt);
            }
        });

        BtnColor.setPreferredSize(SizeColorBox);
        BtnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnColorActionPerformed(evt);
            }
        });

        File.setText("File");

        MenuItemNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
        MenuItemNew.setText("New");
        MenuItemNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemNewActionPerformed(evt);
            }
        });
        File.add(MenuItemNew);

        MenuItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        MenuItemOpen.setText("Open");
        MenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemOpenActionPerformed(evt);
            }
        });
        File.add(MenuItemOpen);

        MenuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        MenuItemSave.setText("Save");
        MenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSaveActionPerformed(evt);
            }
        });
        File.add(MenuItemSave);

        MenuItemSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuItemSaveAs.setText("Save as");
        MenuItemSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSaveAsActionPerformed(evt);
            }
        });
        File.add(MenuItemSaveAs);

        MenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        MenuItemExit.setText("Exit");
        MenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemExitActionPerformed(evt);
            }
        });
        File.add(MenuItemExit);

        MenuBar.add(File);

        View.setText("View");
        MenuBar.add(View);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbBolocCustom, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Filter2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(Filter1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(Filter1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Filter3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Filter2_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addComponent(Filter3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Filter2_3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Filter1_3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Filter3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LbBoloc, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RbtnBlur)
                                    .addComponent(RbtnRadian)
                                    .addComponent(RbtnNone)
                                    .addComponent(RbtnSolbel)
                                    .addComponent(RbtnShape))))
                        .addGap(51, 51, 51)
                        .addComponent(BtnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SliderPen, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(BtnPen, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RbtnCustom)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RbtnGausse)
                                .addGap(127, 127, 127)
                                .addComponent(BtnColor, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(LbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(LbBoloc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(RbtnNone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RbtnBlur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnPen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RbtnRadian))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SliderPen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnColor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RbtnSolbel)
                                .addGap(9, 9, 9)
                                .addComponent(RbtnShape)
                                .addGap(18, 18, 18)
                                .addComponent(RbtnGausse)))
                        .addGap(18, 18, 18)
                        .addComponent(RbtnCustom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addComponent(LbBolocCustom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Filter1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Filter1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Filter1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Filter2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Filter2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Filter2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Filter3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Filter3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Filter3_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(BtnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(32, 32, 32)))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemExitActionPerformed
        
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_MenuItemExitActionPerformed

    private void MenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSaveActionPerformed
        // TODO add your handling code here:
        operatorFile("Save", FILE_SAVE);
    }//GEN-LAST:event_MenuItemSaveActionPerformed

    private void MenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemOpenActionPerformed
        // TODO add your handling code here:
        operatorFile("Open file", FILE_OPEN);
    }//GEN-LAST:event_MenuItemOpenActionPerformed

    private void MenuItemNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemNewActionPerformed
        // TODO add your handling code here:
        
   
    }//GEN-LAST:event_MenuItemNewActionPerformed

    private void MenuItemSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSaveAsActionPerformed
        // TODO add your handling code here:
        operatorFile("Save as", FILE_SAVE_AS);
    }//GEN-LAST:event_MenuItemSaveAsActionPerformed

    private void RbtnNoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnNoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbtnNoneActionPerformed

    private void Filter3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filter3_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Filter3_2ActionPerformed

    private void BtnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProcessActionPerformed
        // TODO add your handling code here:
        processFilter(1);
        this.showImage(bfImage);
        
    }//GEN-LAST:event_BtnProcessActionPerformed

    private void Filter1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filter1_1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Filter1_1ActionPerformed

    
    private void Filter1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filter1_2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Filter1_2ActionPerformed

    private void Filter1_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Filter1_1MouseClicked
        // TODO add your handling code here:
           Filter1_1.setText("");
    }//GEN-LAST:event_Filter1_1MouseClicked

    private void Filter1_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Filter1_2MouseClicked
        // TODO add your handling code here:
        Filter1_2.setText("");
    }//GEN-LAST:event_Filter1_2MouseClicked

    private void Filter1_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Filter1_3MouseClicked
        // TODO add your handling code here:
        Filter1_3.setText("");
    }//GEN-LAST:event_Filter1_3MouseClicked

    private void Filter2_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Filter2_1MouseClicked
        // TODO add your handling code here:
        Filter2_1.setText("");
    }//GEN-LAST:event_Filter2_1MouseClicked

    private void Filter2_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Filter2_2MouseClicked
        // TODO add your handling code here:
        Filter2_2.setText("");
    }//GEN-LAST:event_Filter2_2MouseClicked

    private void Filter2_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Filter2_3MouseClicked
        // TODO add your handling code here:
        Filter2_3.setText("");
    }//GEN-LAST:event_Filter2_3MouseClicked

    private void Filter3_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Filter3_1MouseClicked
        // TODO add your handling code here:
        Filter3_1.setText("");
    }//GEN-LAST:event_Filter3_1MouseClicked

    private void Filter3_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Filter3_2MouseClicked
        // TODO add your handling code here:
        Filter3_2.setText("");
    }//GEN-LAST:event_Filter3_2MouseClicked

    private void Filter3_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Filter3_3MouseClicked
        // TODO add your handling code here:
        Filter3_3.setText("");
    }//GEN-LAST:event_Filter3_3MouseClicked

    private void Filter1_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Filter1_1MouseExited
        // TODO add your handling code here:
        if(Filter1_1.getText().equalsIgnoreCase(""))
            Filter1_1.setText("0");
    }//GEN-LAST:event_Filter1_1MouseExited

    private void Filter1_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Filter1_2MouseExited
        // TODO add your handling code here:
         if(Filter1_2.getText().equalsIgnoreCase(""))
            Filter1_2.setText("0");
    }//GEN-LAST:event_Filter1_2MouseExited

    private void Filter1_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Filter1_3MouseExited
        // TODO add your handling code here:
         if(Filter1_3.getText().equalsIgnoreCase(""))
            Filter1_3.setText("0");
    }//GEN-LAST:event_Filter1_3MouseExited

    private void Filter2_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Filter2_1MouseExited
        // TODO add your handling code here:
         if(Filter2_1.getText().equalsIgnoreCase(""))
            Filter2_1.setText("0");
    }//GEN-LAST:event_Filter2_1MouseExited

    private void Filter2_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Filter2_2MouseExited
        // TODO add your handling code here:
         if(Filter2_2.getText().equalsIgnoreCase(""))
            Filter2_2.setText("0");
    }//GEN-LAST:event_Filter2_2MouseExited

    private void Filter2_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Filter2_3MouseExited
        // TODO add your handling code here:
         if(Filter2_3.getText().equalsIgnoreCase(""))
            Filter2_3.setText("0");
    }//GEN-LAST:event_Filter2_3MouseExited

    private void Filter3_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Filter3_1MouseExited
        // TODO add your handling code here:
         if(Filter3_1.getText().equalsIgnoreCase(""))
            Filter3_1.setText("0");
    }//GEN-LAST:event_Filter3_1MouseExited

    private void Filter3_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Filter3_2MouseExited
        // TODO add your handling code here:
         if(Filter3_2.getText().equalsIgnoreCase(""))
            Filter3_2.setText("0");
    }//GEN-LAST:event_Filter3_2MouseExited

    private void Filter3_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Filter3_3MouseExited
        // TODO add your handling code here:
         if(Filter3_3.getText().equalsIgnoreCase(""))
            Filter3_3.setText("0");
    }//GEN-LAST:event_Filter3_3MouseExited

    private void BtnProcessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnProcessMouseClicked
        // TODO add your handling code here:
        if(RbtnBlur.isSelected())
            System.out.println("Blur");
        if(RbtnCustom.isSelected())
            System.out.println("Custom");
        if(RbtnGausse.isSelected())
            System.out.println("Gausse");
        if(RbtnNone.isSelected())
            System.out.println("None");
        if(RbtnRadian.isSelected())
            System.out.println("Radian");
        if(RbtnShape.isSelected())
            System.out.println("Shape");
       
        if(RbtnSolbel.isSelected())
            System.out.println("Sobel");
    }//GEN-LAST:event_BtnProcessMouseClicked

    private void LbImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbImageMouseClicked
        // TODO add your handling code here:
        if(fileImgae == null)
            operatorFile("File", 1);
       
    }//GEN-LAST:event_LbImageMouseClicked

    private void LbImageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbImageMousePressed
        // TODO add your handling code here:
        if(pen != 1)
        {
            shape.setPoint1(evt.getX(), evt.getY());
            System.out.println(evt.getX() + ": " + getY());
        }else
        {
            old = evt.getPoint();
        }
    }//GEN-LAST:event_LbImageMousePressed

    private void LbImageMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbImageMouseDragged
        // TODO add your handling code here:
            if(pen ==1)
            {
                Graphics2D g = (Graphics2D) bfImage.getGraphics();
                g.setStroke(new BasicStroke((float)SliderPen.getValue()));
                g.setColor(color);
                java.awt.Point temp = evt.getPoint();
                g.drawLine(old.x, old.y,temp.x,temp.y);
                old = temp;
                showImage(bfImage);
                System.out.println("aaa");
            }
            else
            {
                shape.setPoint2(evt.getX(), evt.getY());
                BufferedImage temp = shape.draw(bfImage, color);
                showImage(temp);
            }
            
       
    }//GEN-LAST:event_LbImageMouseDragged

    private void BtnPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPenActionPerformed

    private void BtnPenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPenMouseClicked
        // TODO add your handling code here:
        if(pen == 0)
            pen = 1;
        else
            pen = 0;
        System.out.println(pen);
    }//GEN-LAST:event_BtnPenMouseClicked

    private void BtnPenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPenMouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_BtnPenMouseReleased

    private void SliderPenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderPenStateChanged
        // TODO add your handling code here:
        if(SliderPen.getValueIsAdjusting())
            return;
        System.out.println(SliderPen.getValue());
    }//GEN-LAST:event_SliderPenStateChanged

    private void BtnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnColorActionPerformed
        // TODO add your handling code here:
        color = JColorChooser.showDialog(this.rootPane, "Chọn màu", Color.WHITE);
        BtnColor.setBackground(color);
    }//GEN-LAST:event_BtnColorActionPerformed

    private void Filter1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filter1_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Filter1_3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    public void processFilter(int n)
    {
        
        float[] blurKernel = new float[9];
        switch(n)
        {
            case 1:
            {
                blurKernel = new float[] {
                            1 /9f, 1 /9f, 1 /9f, 
                            1 /9f, 1 /9f, 1 /9f,
                            1 /9f, 1 /9f, 1 /9f
                            };
                break;
            }
            case 2:
            {
                break;
            }
            case 3:
            {
                break;
            }
            case 4:
            {
                break;
            }
            case 5:
            {
                break;
            }
            default:
            {
                
            }
            
            
        }
        BufferedImageOp blur = new ConvolveOp(new Kernel(3, 3, blurKernel));
        BufferedImage bluri = blur.filter(bfImage, new BufferedImage(bfImage.getWidth(), bfImage.getHeight(), bfImage.getType()));
        bfImage = bluri;
    }
    
    public void showImage(BufferedImage bf)
    {
        System.out.println("Show ImageS");
        int x = LbImage.getSize().width;
        int y = LbImage.getSize().height;
        int ix = bf.getWidth();
        int iy = bf.getHeight();
        int dx = 0;
        int dy = 0;
        if(x / y > ix / iy)
        {
            dy = y;
            dx = dy * ix / iy;
        }
        else
        {
            dx = x;
            dy = dx * iy / ix;
        }
        ImageIcon icon = new ImageIcon(bfImage.getScaledInstance(dx, dy, BufferedImage.SCALE_SMOOTH));
        LbImage.setIcon(icon);
    }

    public void operatorFile(String title, int type)
    {
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle(title);
        int chosse = -1;
        
        switch(type)
        {
            case FILE_OPEN:
            {
                chosse = chooser.showOpenDialog(null);
                break;
            }
            case FILE_SAVE:
            {
                chosse = chooser.showSaveDialog(null);
                break;
            }
            case FILE_SAVE_AS:
            {
                chosse = chooser.showSaveDialog(null);
                break;
            }
        }
        if (chosse == JFileChooser.APPROVE_OPTION)
        {
             switch(type)
        {
            case FILE_OPEN:
            {
                fileImgae =chooser.getSelectedFile();
                 try {
                     bfImage = ImageIO.read(fileImgae);
                     int x = LbImage.getSize().width;
                     int y = LbImage.getSize().height;
                     int ix = bfImage.getWidth();
                     int iy = bfImage.getHeight();
                     int dx = 0;
                     int dy = 0;
                     if(x / y > ix / iy)
                     {
                         dy = y;
                         dx = dy * ix / iy;
                     }
                     else
                     {
                         dx = x;
                         dy = dx * iy / ix;
                     }
                     ImageIcon icon = new ImageIcon(bfImage.getScaledInstance(dx, dy, bfImage.SCALE_SMOOTH));
                     LbImage.setIcon(icon);
                     
                 } catch (IOException ex) {
                     Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                 }
                
                break;
            }
            case FILE_SAVE:
            {
                
                break;
            }
            case FILE_SAVE_AS:
            {
               
                break;
            }
        }
        }
    }
    private final int FILE_OPEN = 1;
    private final int FILE_SAVE = 2;
    private final int FILE_SAVE_AS = 3;
    private int pen = 0;
    private java.awt.Point old;
    private File fileImgae = null;
    BufferedImage bfImage = null;
    private  Color color = null;
    private  Shape shape = new Rectangle();
    Dimension SizeColorBox = new Dimension(20, 20);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnColor;
    private javax.swing.JButton BtnProcess;
    private javax.swing.JMenu File;
    private javax.swing.JTextField Filter1_1;
    private javax.swing.JTextField Filter1_2;
    private javax.swing.JTextField Filter1_3;
    private javax.swing.JTextField Filter2_1;
    private javax.swing.JTextField Filter2_2;
    private javax.swing.JTextField Filter2_3;
    private javax.swing.JTextField Filter3_1;
    private javax.swing.JTextField Filter3_2;
    private javax.swing.JTextField Filter3_3;
    private javax.swing.JLabel LbBoloc;
    private javax.swing.JLabel LbBolocCustom;
    private javax.swing.JLabel LbImage;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem MenuItemExit;
    private javax.swing.JMenuItem MenuItemNew;
    private javax.swing.JMenuItem MenuItemOpen;
    private javax.swing.JMenuItem MenuItemSave;
    private javax.swing.JMenuItem MenuItemSaveAs;
    private javax.swing.JRadioButton RbtnBlur;
    private javax.swing.JRadioButton RbtnCustom;
    private javax.swing.JRadioButton RbtnGausse;
    private javax.swing.JRadioButton RbtnNone;
    private javax.swing.JRadioButton RbtnRadian;
    private javax.swing.JRadioButton RbtnShape;
    private javax.swing.JRadioButton RbtnSolbel;
    private javax.swing.JSlider SliderPen;
    private javax.swing.JMenu View;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
